In [1]:
!pip install numpy

In [7]:
import numpy as np

multi_arrayA = np.array([[0,1],[2,3],[4,5]])

import numpy as np

multi_arrayA = np.array([[0,1],[2,3],[4,5]])

multi_arrayB = np.array([[0,1,2,3],[4,5,6,7]])

print(f'"A=" {multi_arrayA}')

print(f'"B=" {multi_arrayB}')


"A=" [[0 1]
 [2 3]
 [4 5]]
"B=" [[0 1 2 3]
 [4 5 6 7]]


In [11]:
#np.dot(a,b)で行列aと行列bの積

result = np.dot(multi_arrayA, multi_arrayB)

print(result)


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [13]:
#計算された行列の最大値を求めて表示

result.max()


np.int64(47)